# Generated by Django 5.0 on 2024-01-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='aaa@gmail.com', max_length=254),
        ),
    ]
